services:
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  tests:
    build: .
    command: pytest -v --disable-warnings
    env_file:
      - .env.test
    volumes:
      - .:/app
    depends_on:
      - test_db
    working_dir: /app
