# Generated by Django 5.1.7 on 2025-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="url",
            field=models.URLField(blank=True, verbose_name="Посилання на зображення"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Банківська карта"), ("crypto", "Криптовалюта")],
                max_length=20,
                verbose_name="Метод оплати",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="code",
            field=models.CharField(
                choices=[
                    ("free", "Безкоштовний"),
                    ("basic", "Базовий"),
                    ("pro", "Професійний"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Код тарифу",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Рівень тарифу (1 - безкоштовний, 2 - базовий, 3 - профі)",
            ),
        ),
    ]
