# Generated by Django 5.1.7 on 2025-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_postimage_url_alter_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="is_trial",
        ),
        migrations.AddField(
            model_name="tariff",
            name="is_trial",
            field=models.BooleanField(default=False, verbose_name="Тестовий період"),
        ),
        migrations.AddField(
            model_name="tariff",
            name="trial_duration_days",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Тривалість тестового періоду (днів)"
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="features",
            field=models.JSONField(
                default=dict,
                help_text="Напр. {'channels': 3, 'sources': 5, 'generations': 300}",
                verbose_name="Особливості тарифу",
            ),
        ),
    ]
