# Generated by Django 5.1.7 on 2025-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0005_remove_tariff_features_remove_tariff_is_trial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="pay_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="trial_duration_days",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Тривалість тестового періоду (днів)"
            ),
        ),
    ]
