# Generated by Django 5.1.7 on 2025-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_remove_post_is_draft_remove_post_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оригiнальної публікації'),
        ),
    ]
