# Generated by Django 5.1.7 on 2025-05-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_aisettings_role_alter_aisettings_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='role_content',
            field=models.TextField(blank=True, verbose_name='Текст роли'),
        ),
    ]
