# Generated by Django 5.1.7 on 2025-09-15 08:06

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = []

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID каналу"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва каналу")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Опис каналу"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "notifications",
                    models.BooleanField(default=False, verbose_name="Сповiщення"),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Europe/Kiev", "🇺🇦 Київ (UTC+2)"),
                            ("Europe/London", "🇪🇺 Лондон (UTC+0)"),
                            ("America/New_York", "🇺🇸 Нью-Йорк (UTC-4)"),
                        ],
                        default="Europe/Kiev",
                        max_length=50,
                        verbose_name="Часовий пояс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Канали",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Ім'я"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Прізвище"
                    ),
                ),
                (
                    "subscription_status",
                    models.BooleanField(default=False, verbose_name="Статус підписки"),
                ),
                (
                    "subscription_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата закінчення підписки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип підписки"
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва флоу")),
                ("theme", models.CharField(max_length=100, verbose_name="Тематика")),
                (
                    "sources",
                    models.JSONField(default=list, verbose_name="Джерела контенту"),
                ),
                (
                    "content_length",
                    models.CharField(
                        choices=[
                            ("to_100", "До 100 знаків"),
                            ("to_300", "До 300 знаків"),
                            ("to_1000", "До 1000 знаків"),
                        ],
                        max_length=50,
                        verbose_name="Обсяг тексту",
                    ),
                ),
                (
                    "use_emojis",
                    models.BooleanField(
                        default=False, verbose_name="Використання емодзі"
                    ),
                ),
                (
                    "use_premium_emojis",
                    models.BooleanField(default=False, verbose_name="Преміум емодзі"),
                ),
                (
                    "title_highlight",
                    models.BooleanField(
                        default=False, verbose_name="Виділення заголовків"
                    ),
                ),
                (
                    "cta",
                    models.BooleanField(
                        default=False, verbose_name="Заклик до дії (CTA)"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Кожну годину"),
                            ("12h", "Раз на 12 год"),
                            ("daily", "Раз на день"),
                        ],
                        max_length=50,
                        verbose_name="Частота генерації",
                    ),
                ),
                (
                    "signature",
                    models.TextField(blank=True, verbose_name="Підпис до постів"),
                ),
                (
                    "flow_volume",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Кількість постів у флоу"
                    ),
                ),
                (
                    "ad_time",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Час для рекламних топів (HH:MM)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "next_generation_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Наступна генерація"
                    ),
                ),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Остання генерація"
                    ),
                ),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Флоу",
                "verbose_name_plural": "Флоу",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Промпт")),
                (
                    "role",
                    models.CharField(blank=True, max_length=255, verbose_name="Роль"),
                ),
                (
                    "role_content",
                    models.TextField(blank=True, verbose_name="Текст роли"),
                ),
                (
                    "style",
                    models.CharField(blank=True, max_length=100, verbose_name="Стиль"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "flow",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="admin_panel.flow",
                        verbose_name="Флоу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування AI",
                "verbose_name_plural": "Налаштування AI",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "original_content",
                    models.TextField(
                        blank=True, default="", verbose_name="Оригiнальний текст"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Чернетка"),
                            ("scheduled", "Заплановано"),
                            ("published", "Опубліковано"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="Ідентифікатор посту в оригінальному джерелі (Telegram/Web)",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Унікальний ID із джерела",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Посилання на джерело"
                    ),
                ),
                (
                    "original_link",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Посилання на оригiнальний пост",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публікації"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланований час"
                    ),
                ),
                (
                    "original_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата оригiнальної публікації",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="admin_panel.flow",
                        verbose_name="Флоу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Пости",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=255,
                        upload_to="posts/images/",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_panel.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення поста",
                "verbose_name_plural": "Зображення постів",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PostVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        max_length=255, upload_to="posts/videos/", verbose_name="Вiдео"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="admin_panel.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вiдео поста",
                "verbose_name_plural": "Вiдео постів",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(max_length=50, verbose_name="Тип підписки"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата початку"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="Дата закінчення")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="admin_panel.channel",
                        verbose_name="Канал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Підписка",
                "verbose_name_plural": "Підписки",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_posts",
                    models.IntegerField(default=0, verbose_name="Всього постів"),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="Всього переглядів"),
                ),
                (
                    "total_likes",
                    models.IntegerField(default=0, verbose_name="Всього лайків"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Останнє оновлення"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="admin_panel.channel",
                        verbose_name="Канал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистика",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сума"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Метод оплати"),
                ),
                (
                    "payment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата оплати"),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=False, verbose_name="Успішний"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платіж",
                "verbose_name_plural": "Платежі",
            },
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="admin_panel.post",
                        verbose_name="Пост",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чернетка",
                "verbose_name_plural": "Чернетки",
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="admin_panel.user",
                verbose_name="Користувач",
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["channel", "created_at"], name="admin_panel_channel_c7f83f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(fields=["name"], name="admin_panel_name_f8ebda_idx"),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id__isnull", False)),
                fields=("source_id",),
                name="unique_source_id",
            ),
        ),
    ]
