# Generated by Django 5.1.7 on 2025-03-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, unique=True, verbose_name='ID каналу')),
                ('name', models.CharField(max_length=255, verbose_name='Назва каналу')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис каналу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Канали',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я користувача")),
                ('subscription_status', models.BooleanField(default=False, verbose_name='Статус підписки')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закінчення підписки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва флоу')),
                ('theme', models.CharField(max_length=100, verbose_name='Тематика')),
                ('source', models.CharField(max_length=100, verbose_name='Джерело контенту')),
                ('content_length', models.CharField(max_length=50, verbose_name='Обсяг тексту')),
                ('use_emojis', models.BooleanField(default=False, verbose_name='Використання емодзі')),
                ('use_premium_emojis', models.BooleanField(default=False, verbose_name='Використання преміум емодзі')),
                ('cta', models.BooleanField(default=False, verbose_name='Заклик до дії (CTA)')),
                ('frequency', models.CharField(max_length=50, verbose_name='Частота генерації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='admin_panel.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Флоу',
                'verbose_name_plural': 'Флоу',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Посилання на джерело')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='admin_panel.flow', verbose_name='Флоу')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=50, verbose_name='Тип підписки')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(verbose_name='Дата закінчення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='admin_panel.channel', verbose_name='Канал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='admin_panel.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Підписка',
                'verbose_name_plural': 'Підписки',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField(default=0, verbose_name='Всього постів')),
                ('total_views', models.IntegerField(default=0, verbose_name='Всього переглядів')),
                ('total_likes', models.IntegerField(default=0, verbose_name='Всього лайків')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='admin_panel.channel', verbose_name='Канал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='admin_panel.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Метод оплати')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплати')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Успішний')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admin_panel.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admin_panel.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='admin_panel.post', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='admin_panel.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Чернетка',
                'verbose_name_plural': 'Чернетки',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='admin_panel.user', verbose_name='Користувач'),
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Промпт')),
                ('style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='admin_panel.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Налаштування AI',
                'verbose_name_plural': 'Налаштування AI',
            },
        ),
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Дія')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата дії')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_panel', to='admin_panel.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Адмін-панель',
                'verbose_name_plural': 'Адмін-панель',
            },
        ),
    ]
