# Generated by Django 5.1.7 on 2025-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип підписки'),
        ),
    ]
