# Generated by Django 5.1.7 on 2025-03-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Канали'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': 'Флоу', 'verbose_name_plural': 'Флоу'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID каналу'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(max_length=100, verbose_name='Назва каналу'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.channel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва флоу'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='parameters',
            field=models.JSONField(verbose_name='Параметри'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='source_type',
            field=models.CharField(max_length=50, verbose_name='Тип джерела'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Вміст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='post',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flow', verbose_name='Флоу'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланований час'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на джерело'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='draft', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закінчення підписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_status',
            field=models.BooleanField(default=False, verbose_name='Статус підписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я користувача"),
        ),
    ]
