# Generated by Django 5.1.7 on 2025-09-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="ad_time",
        ),
        migrations.AlterField(
            model_name="post",
            name="source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Посилання на джерело"
            ),
            preserve_default=False,
        ),
    ]
