# Generated by Django 5.1.7 on 2025-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Флоу",
                "verbose_name_plural": "Флоу",
            },
        ),
        migrations.RemoveField(
            model_name="flow",
            name="source",
        ),
        migrations.AddField(
            model_name="flow",
            name="ad_time",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                verbose_name="Час для рекламних топів (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="flow_volume",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name="Кількість постів у флоу"
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="signature",
            field=models.TextField(
                blank=True, null=True, verbose_name="Підпис до постів"
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="sources",
            field=models.JSONField(default=list, verbose_name="Джерела контенту"),
        ),
        migrations.AddField(
            model_name="flow",
            name="title_highlight",
            field=models.BooleanField(
                default=False, verbose_name="Виділення заголовків"
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
        ),
        migrations.AlterField(
            model_name="flow",
            name="content_length",
            field=models.CharField(
                choices=[
                    ("short", "Короткий (до 300 знаків)"),
                    ("medium", "Середній (300-1000 знаків)"),
                    ("long", "Довгий (понад 1000 знаків)"),
                ],
                max_length=50,
                verbose_name="Обсяг тексту",
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("hourly", "Кожну годину"),
                    ("daily", "Раз на день"),
                    ("weekly", "Раз на тиждень"),
                    ("custom", "Користувацький графік"),
                ],
                max_length=50,
                verbose_name="Частота генерації",
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="use_premium_emojis",
            field=models.BooleanField(default=False, verbose_name="Преміум емодзі"),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["channel", "created_at"], name="admin_panel_channel_c7f83f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(fields=["name"], name="admin_panel_name_f8ebda_idx"),
        ),
    ]
