# Generated by Django 5.1.7 on 2025-09-15 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_remove_flow_ad_time_alter_post_source_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postvideo",
            old_name="image",
            new_name="video",
        ),
    ]
