# Generated by Django 5.1.7 on 2025-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_flow_options_remove_flow_source_flow_ad_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'HOURLY'), ('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('custom', 'CUSTOM')], default='daily', max_length=20),
        ),
    ]
