# Generated by Django 5.1.7 on 2025-03-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_user_subscription_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPanel',
        ),
    ]
