# Generated by Django 5.1.7 on 2025-03-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_delete_adminpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
