# Generated by Django 5.1.7 on 2025-04-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_flow_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.channel'),
        ),
    ]
