# Generated by Django 5.1.7 on 2025-03-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_user_first_name_user_last_name_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
