# Generated by Django 5.1.7 on 2025-04-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_flow_is_auto_generated_flow_last_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='is_auto_generated',
        ),
    ]
