# Generated by Django 5.1.7 on 2025-04-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0009_remove_flow_is_auto_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
