# Generated by Django 5.1.7 on 2025-05-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_panel",
            "0012_alter_aisettings_user_alter_flow_content_length_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aisettings",
            name="user",
        ),
        migrations.AddField(
            model_name="aisettings",
            name="flow",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_settings",
                to="admin_panel.flow",
                verbose_name="Флоу",
            ),
        ),
    ]
