# Generated by Django 5.1.7 on 2025-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_remove_aisettings_user_aisettings_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('scheduled', 'Заплановано'), ('published', 'Опубліковано')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланований час'),
        ),
    ]
