# Generated by Django 5.1.7 on 2025-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0016_post_original_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="source_id",
            field=models.CharField(
                blank=True,
                help_text="Ідентифікатор посту в оригінальному джерелі (Telegram/Web)",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Унікальний ID із джерела",
            ),
        ),
    ]
