# Generated by Django 5.1.7 on 2025-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0020_aisettings_role_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="notifications",
            field=models.BooleanField(default=False, verbose_name="Сповiщення"),
        ),
    ]
