# Generated by Django 5.1.7 on 2025-09-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0022_channel_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Опис каналу"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flow",
            name="ad_time",
            field=models.CharField(
                blank=True,
                default="",
                max_length=5,
                verbose_name="Час для рекламних топів (HH:MM)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flow",
            name="signature",
            field=models.TextField(
                blank=True, default="", verbose_name="Підпис до постів"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Ім'я"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Прізвище"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="payment_method",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription_type",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Тип підписки"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Telegram username"
            ),
            preserve_default=False,
        ),
    ]
