# Generated by Django 5.1.7 on 2025-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0023_alter_channel_description_alter_flow_ad_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="original_content",
            field=models.TextField(
                blank=True, default="", verbose_name="Оригiнальний текст"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="original_link",
            field=models.CharField(
                blank=True, default="", verbose_name="Посилання на оригiнальний пост"
            ),
            preserve_default=False,
        ),
    ]
