# Generated by Django 5.1.7 on 2025-09-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0024_alter_post_original_content_alter_post_original_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="original_content",
            field=models.TextField(
                blank=True, default="", verbose_name="Оригiнальний текст"
            ),
        ),
    ]
