# Generated by Django 5.1.7 on 2025-09-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0025_alter_post_original_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
        migrations.CreateModel(
            name="PostVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        max_length=255, upload_to="posts/videos/", verbose_name="Вiдео"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="admin_panel.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вiдео поста",
                "verbose_name_plural": "Вiдео постів",
                "ordering": ["order"],
            },
        ),
    ]
