# Generated by Django 5.1.7 on 2025-11-04 10:33

import admin_panel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID каналу"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва каналу")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Опис каналу"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "notifications",
                    models.BooleanField(default=False, verbose_name="Сповiщення"),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Europe/Kiev", "🇺🇦 Київ (UTC+2)"),
                            ("Europe/London", "🇪🇺 Лондон (UTC+0)"),
                            ("America/New_York", "🇺🇸 Нью-Йорк (UTC-4)"),
                        ],
                        default="Europe/Kiev",
                        max_length=50,
                        verbose_name="Часовий пояс",
                    ),
                ),
                (
                    "title_emoji",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Емодзі перед заголовком",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Канали",
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код тарифу"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Назва")),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Рівень тарифу (1 - безкоштовний, 2 - базовий, 3 - профі)",
                    ),
                ),
                (
                    "channels_available",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Доступно каналів"
                    ),
                ),
                (
                    "sources_available",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Доступно джерел"
                    ),
                ),
                (
                    "generations_available",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Достпуно генерацій"
                    ),
                ),
                (
                    "platforms",
                    models.CharField(
                        choices=[
                            ("tg", "Telegram"),
                            ("web", "Web"),
                            ("both", "Telegram + Web"),
                        ],
                        default="tg",
                        max_length=10,
                        verbose_name="Платформи",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "trial_duration_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Тривалість тестового періоду (днів)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифи",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Ім'я"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Прізвище"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "generated_posts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кількість генерацій"
                    ),
                ),
                (
                    "generation_reset_at",
                    models.DateTimeField(
                        blank=True,
                        default=admin_panel.models.default_generation_reset_at,
                        null=True,
                        verbose_name="Час наступного скидання генерацій",
                    ),
                ),
            ],
            options={
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва флоу")),
                ("theme", models.CharField(max_length=100, verbose_name="Тематика")),
                (
                    "sources",
                    models.JSONField(default=list, verbose_name="Джерела контенту"),
                ),
                (
                    "content_length",
                    models.CharField(
                        choices=[
                            ("to_100", "До 100 знаків"),
                            ("to_300", "До 300 знаків"),
                            ("to_1000", "До 1000 знаків"),
                        ],
                        max_length=50,
                        verbose_name="Обсяг тексту",
                    ),
                ),
                (
                    "use_emojis",
                    models.BooleanField(
                        default=False, verbose_name="Використання емодзі"
                    ),
                ),
                (
                    "use_premium_emojis",
                    models.BooleanField(default=False, verbose_name="Преміум емодзі"),
                ),
                (
                    "title_highlight",
                    models.BooleanField(
                        default=False, verbose_name="Виділення заголовків"
                    ),
                ),
                (
                    "cta",
                    models.BooleanField(
                        default=False, verbose_name="Заклик до дії (CTA)"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Кожну годину"),
                            ("12h", "Раз на 12 год"),
                            ("daily", "Раз на день"),
                        ],
                        max_length=50,
                        verbose_name="Частота генерації",
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Підпис до постів",
                    ),
                ),
                (
                    "flow_volume",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Кількість постів у флоу"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "next_generation_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Наступна генерація"
                    ),
                ),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Остання генерація"
                    ),
                ),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Флоу",
                "verbose_name_plural": "Флоу",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Промпт")),
                (
                    "role",
                    models.CharField(blank=True, max_length=255, verbose_name="Роль"),
                ),
                (
                    "role_content",
                    models.TextField(blank=True, verbose_name="Текст роли"),
                ),
                (
                    "style",
                    models.CharField(blank=True, max_length=100, verbose_name="Стиль"),
                ),
                (
                    "use_custom_prompt",
                    models.BooleanField(
                        default=True,
                        verbose_name="Використовувати пользовательский промпт",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "flow",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="admin_panel.flow",
                        verbose_name="Флоу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування AI",
                "verbose_name_plural": "Налаштування AI",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "original_content",
                    models.TextField(
                        blank=True, default="", verbose_name="Оригiнальний текст"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Чернетка"),
                            ("scheduled", "Заплановано"),
                            ("published", "Опубліковано"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="Ідентифікатор посту в оригінальному джерелі (Telegram/Web)",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Унікальний ID із джерела",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, verbose_name="Посилання на джерело"),
                ),
                (
                    "original_link",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Посилання на оригiнальний пост",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публікації"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланований час"
                    ),
                ),
                (
                    "original_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата оригiнальної публікації",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="admin_panel.flow",
                        verbose_name="Флоу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Пости",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=255,
                        upload_to="posts/images/",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, verbose_name="Посилання на зображення"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_panel.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення поста",
                "verbose_name_plural": "Зображення постів",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PostVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        max_length=255, upload_to="posts/videos/", verbose_name="Вiдео"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="admin_panel.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вiдео поста",
                "verbose_name_plural": "Вiдео постів",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Промокод"
                    ),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 місяць"),
                            (6, "6 місяців"),
                            (9, "9 місяців"),
                            (12, "1 рік"),
                        ],
                        verbose_name="Термін підписки",
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Відсоток знижки від 0 до 100",
                        verbose_name="Знижка (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_codes",
                        to="admin_panel.tariff",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоди",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TariffPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 місяць"),
                            (6, "6 місяців"),
                            (9, "9 місяців"),
                            (12, "1 рік"),
                        ],
                        verbose_name="Термін підписки",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="admin_panel.tariff",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Термін тарифу",
                "verbose_name_plural": "Терміни тарифів",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата початку"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="Дата закінчення")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "tariff_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="admin_panel.tariffperiod",
                        verbose_name="Тариф + період",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Підписка",
                "verbose_name_plural": "Підписки",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_posts",
                    models.IntegerField(default=0, verbose_name="Всього постів"),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="Всього переглядів"),
                ),
                (
                    "total_likes",
                    models.IntegerField(default=0, verbose_name="Всього лайків"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Останнє оновлення"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="admin_panel.channel",
                        verbose_name="Канал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистика",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сума"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Банківська карта"),
                            ("crypto", "Криптовалюта"),
                        ],
                        max_length=20,
                        verbose_name="Метод оплати",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата оплати"),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=False, verbose_name="Успішний"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("pay_url", models.URLField(blank=True)),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="admin_panel.promocode",
                        verbose_name="Промокод",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="admin_panel.subscription",
                        verbose_name="Підписка",
                    ),
                ),
                (
                    "tariff_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="admin_panel.tariffperiod",
                        verbose_name="Тарифний період",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платіж",
                "verbose_name_plural": "Платежі",
            },
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="admin_panel.post",
                        verbose_name="Пост",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="admin_panel.user",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чернетка",
                "verbose_name_plural": "Чернетки",
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="admin_panel.user",
                verbose_name="Користувач",
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["channel", "created_at"], name="admin_panel_channel_c7f83f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(fields=["name"], name="admin_panel_name_f8ebda_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["flow", "-created_at"], name="admin_panel_flow_id_42070c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["source_id"], name="admin_panel_source__60f68d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "scheduled_time"],
                name="admin_panel_status_31ae21_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id__isnull", False)),
                fields=("source_id",),
                name="unique_source_id",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tariffperiod",
            unique_together={("tariff", "months")},
        ),
    ]
