# Generated by Django 5.1.7 on 2025-11-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tariff",
            options={"verbose_name": "Тариф", "verbose_name_plural": "Тарифи"},
        ),
        migrations.RemoveField(
            model_name="tariff",
            name="level",
        ),
    ]
