# Generated by Django 5.1.2 on 2025-11-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_tariff_options_remove_tariff_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('months', models.PositiveSmallIntegerField(choices=[(1, '1 місяць'), (6, '6 місяців'), (9, '9 місяців'), (12, '12 місяців')], verbose_name='Термін підписки')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Відсоток знижки від 0 до 100', verbose_name='Знижка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='admin_panel.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['tariff'], name='admin_panel_tariff_id_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['-created_at'], name='admin_panel_created_at_idx'),
        ),
    ]
