# Generated by Django 5.1.2 on 2025-11-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='payments',
                to='admin_panel.promocode',
                verbose_name='Промокод'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['promo_code'], name='admin_panel_promo_code_id_idx'),
        ),
    ]
