# Generated by Django 5.1.7 on 2025-09-17 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0003_remove_subscription_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="payment_method",
        ),
    ]
