# Generated by Django 5.1.7 on 2025-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0004_remove_user_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tariff",
            name="features",
        ),
        migrations.RemoveField(
            model_name="tariff",
            name="is_trial",
        ),
        migrations.AddField(
            model_name="tariff",
            name="channels_available",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Доступно каналів"
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="generations_available",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Достпуно генерацій"
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="platforms",
            field=models.CharField(
                choices=[
                    ("tg", "Telegram"),
                    ("web", "Web"),
                    ("both", "Telegram + Web"),
                ],
                default="tg",
                max_length=10,
                verbose_name="Платформи",
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="sources_available",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Доступно джерел"
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="trial_duration_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Тривалість тестового періоду (днів) для безкоштовного тарифу",
            ),
        ),
    ]
