# Generated by Django 5.1.7 on 2025-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_payment_promo_code"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="admin_panel_promo_code_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="promocode",
            name="admin_panel_tariff_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="promocode",
            name="admin_panel_created_at_idx",
        ),
        migrations.AddField(
            model_name="promocode",
            name="gives_free_subscription",
            field=models.BooleanField(
                default=False,
                help_text="Якщо так, підписка активується одразу без оплати",
                verbose_name="Дає безкоштовну підписку",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="months",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 місяць"),
                    (6, "6 місяців"),
                    (9, "9 місяців"),
                    (12, "1 рік"),
                ],
                verbose_name="Термін підписки",
            ),
        ),
    ]
