# Generated by Django 5.1.7 on 2025-11-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_remove_payment_admin_panel_promo_code_id_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="gives_free_subscription",
        ),
    ]
