# Generated by Django 5.1.7 on 2025-11-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_remove_promocode_gives_free_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="discount_percent",
        ),
    ]
