# Generated by Django 5.1.7 on 2025-09-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0006_payment_order_id_payment_pay_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="generated_posts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кількість генерацій"
            ),
        ),
    ]
