# Generated by Django 5.1.7 on 2025-11-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_remove_promocode_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(default=False, verbose_name="Пробний період"),
        ),
    ]
