
WEB_SOURCES = [
    "https://top-channel.tv/",
    "https://www.derstandard.at/",
    "https://orf.at/",
    "https://www.standaard.be/",
    "https://www.lesoir.be/",
    "https://www.klix.ba/",
    "https://www.jutarnji.hr/",
    "https://www.seznamzpravy.cz/",
    "https://www.idnes.cz/zpravy",
    "https://ct24.ceskatelevize.cz/",
    "https://www.dr.dk/nyheder",
    "https://news.err.ee/",
    "https://postimees.ee/",
    "https://yle.fi/news",
    "https://www.france24.com/en/france",
    "https://www.lefigaro.fr/",
    "https://www.lemonde.fr/",
    "https://www.spiegel.de/international/",
    "https://www.faz.net/aktuell/",
    "https://www.handelsblatt.com/",
    "https://www.sueddeutsche.de/",
    "https://www.tagesschau.de/",
    "https://hvg.hu/",
    "https://telex.hu/",
    "https://www.rte.ie/news/",
    "https://www.irishtimes.com/news/",
    "https://www.ansa.it/",
    "https://www.corriere.it/",
    "https://www.repubblica.it/",
    "https://www.delfi.lv/",
    "https://www.lsm.lv/",
    "https://www.delfi.lt/",
    "https://www.lrt.lt/",
    "https://www.wort.lu/",
    "https://www.vijesti.me/",
    "https://nos.nl/",
    "https://www.nrc.nl/",
    "https://mia.mk/",
    "https://www.aftenposten.no/",
    "https://www.nrk.no/nyheter/",
    "https://www.bbc.com/news/world/europe",
    "https://balkaninsight.com/",
    "https://www.dw.com/en/top-stories/europe/s-1432",
    "https://euobserver.com/",
    "https://www.euronews.com/news",
    "https://www.ft.com/world/europe",
    "https://www.politico.eu/",
    "https://www.reuters.com/world/europe/",
    "https://wyborcza.pl/",
    "https://www.pap.pl/",
    "https://www.polsatnews.pl/",
    "https://www.rp.pl/",
    "https://tvn24.pl/",
    "https://observador.pt/",
    "https://www.publico.pt/",
    "https://n1info.rs/",
    "https://www.rts.rs/",
    "https://dennikn.sk/",
    "https://www.sme.sk/",
    "https://www.delo.si/",
    "https://www.elmundo.es/",
    "https://elpais.com/",
    "https://www.rtve.es/noticias/",
    "https://www.dn.se/",
    "https://www.svt.se/nyheter/",
    "https://www.nzz.ch/",
    "https://news.sky.com/uk",
    "https://www.theguardian.com/uk-news",
    "https://www.independent.co.uk/news/uk",
    "https://www.telegraph.co.uk/news/",
    "https://24tv.ua/",
    "https://armyinform.com.ua/category/novyny/",
    "https://www.bbc.com/ukrainian",
    "https://babel.ua/news",
    "https://censor.net/ua/news",
    "https://espreso.tv/news",
    "https://forbes.ua/news",
    "https://glavcom.ua/news",
    "https://gordonua.com/news.html",
    "https://hromadske.ua/",
    "https://hromadske.radio/news",
    "https://interfax.com.ua/news/",
    "https://kyivindependent.com/",
    "https://www.kyivpost.com/",
    "https://lb.ua/news",
    "https://www.liga.net/news",
    "https://mil.in.ua/uk/news/",
    "https://mind.ua/news",
    "https://nv.ua/ukr/ukraine",
    "https://www.rbc.ua/ukr/news",
    "https://suspilne.media/news/",
    "https://tsn.ua/",
    "https://www.unian.ua/",
    "https://tyzhden.ua/News/",
    "https://www.pravda.com.ua/news/",
    "https://www.ukrinform.ua/block-lastnews",
    "https://zn.ua/",
    "https://www.eurointegration.com.ua/news/",
    "https://www.epravda.com.ua/news/",
    "https://www.radiosvoboda.org/z/1041"
]

TELEGRAM_SOURCES = [
    "https://t.me/ukrpravda_news",
    "https://t.me/suspilnenews",
    "https://t.me/hromadske_ua",
    "https://t.me/nvua_official",
    "https://t.me/censor_net",
    "https://t.me/europravda",
    "https://t.me/spravdi",
    "https://t.me/znua_live",
    "https://t.me/bbc_ukrainian",
    "https://t.me/kyivindependent_official",
    "https://t.me/KyivPost",
    "https://t.me/liganet",
    "https://t.me/lbua",
    "https://t.me/textyorgua",
    "https://t.me/rubryka",
    "https://t.me/AFUStratCom",
    "https://t.me/DIUkraine",
    "https://t.me/SBUkr",
    "https://t.me/landforcesofukraine",
    "https://t.me/GeneralStaffZSU",
    "https://t.me/dsns_telegram",
    "https://t.me/DPSU_ua",
    "https://t.me/Forbes_Ukraine_official",
    "https://t.me/svidomi_ua",
    "https://t.me/doucommunity",
    "https://t.me/uaobozrevatel",
    "https://t.me/RBC_ua_news",
    "https://t.me/radiosvoboda",
    "https://t.me/babel",
    "https://t.me/espresotb",
    "https://t.me/channel24_ua",
    "https://t.me/FAKTY_ICTV",
    "https://t.me/TCH_channel",
    "https://t.me/ukraina24tv",
    "https://t.me/mvs_ukraine",
    "https://t.me/dsszzi_official",
    "https://t.me/mozofficial",
    "https://t.me/mintsyfra",
    "https://t.me/UA_National_Police",
    "https://t.me/nbu_ua",
    "https://t.me/armyofukraine",
    "https://t.me/UkraineNOW",
    "https://t.me/suspilnesport",
    "https://t.me/suspilnevideo",
    "https://t.me/suspilnekultura",
    "https://t.me/ukrinform",
    "https://t.me/interfaxukraine",
    "https://t.me/villageua",
    "https://t.me/uniannet",
    "https://t.me/radionv",
    "https://t.me/europravda_en",
    "https://t.me/tyzhdenua",
    "https://t.me/nvbusiness",
    "https://t.me/epravda",
    "https://t.me/forbes_ukraine_business",
    "https://t.me/devua",
    "https://t.me/suspilnekharkiv",
    "https://t.me/suspilnelviv",
    "https://t.me/suspilneodesa",
    "https://t.me/suspilnednipro",
    "https://t.me/lvivoda",
    "https://t.me/vinnytskaODA",
    "https://t.me/volynskaODA",
    "https://t.me/dnipropetrovskaODA",
    "https://t.me/pavlokyrylenko_donoda",
    "https://t.me/zhytomyrskaODA",
    "https://t.me/zakarpatskaODA",
    "https://t.me/starukhofficial",
    "https://t.me/ministry_of_defense_ua",
    "https://t.me/MFA_of_Ukraine",
    "https://t.me/kpszsu",
    "https://t.me/TerritorialDefenseForces",
    "https://t.me/dpsukr",
    "https://t.me/ukrainer",
    "https://t.me/prometheusmooc",
    "https://t.me/+2Lj2_cNoZucxMWFi",
    "https://t.me/+PaKqKz0SpJk0N2Ey",
    "https://t.me/+o7w11vBr5to5MTEy",
    "https://t.me/+aES09d2_vj9hMGNi",
    "https://t.me/+Y0Mz6L0LTM42ZmYy",
    "https://t.me/+0ieWoWg65ApiZDQy",
    "https://t.me/+tnseLcnbg9QwNWIy",
    "https://t.me/+dRkEZit79lxjODUy",
    "https://t.me/+_Xa2Zz-Wir40MzUy",
    "https://t.me/+E3sPK2CR_RMxNzM1",
    "https://t.me/+V4thnxml9SI5pEMF",
    "https://t.me/+x3A2lVBy6MdkMjg6",
    "https://t.me/+Nf4rbRyLI4k3NzRi",
    "https://t.me/+h_PKcgQbVmM5M2Ni",
    "https://t.me/+KN4YLo7eyQo2YTMy",
    "https://t.me/+YeUvTvW7pys4OWQ6",
    "https://t.me/+rGtYxv_J5jkzOTQ6",
    "https://t.me/+wvoHDXf8Xro0ZmYy",
    "https://t.me/+7Wb2z1klhkdmZWNi",
    "https://t.me/+Iw3yDiB1pb80NTNi",
    "https://t.me/+1QWz4CKKyr9lMDVi",
    "https://t.me/+w0FE-8kXS-dkZGI6",
    "https://t.me/+Kg1a-aRv1jo1Yzg6",
    "https://t.me/+X2Wwe1FTKzc0NzRi",
    "https://t.me/+Hl-eevfuUrlmNjdi"
]

# Категоризированные источники (опционально)
CATEGORIZED_SOURCES = {
    'news': [
        "https://www.bbc.com/news/world/europe",
        "https://www.reuters.com/world/europe/",
        "https://www.nytimes.com/",
        "https://www.theguardian.com/uk-news",
        # ... другие новостные
    ],
    'ukrainian': [
        "https://www.pravda.com.ua/news/",
        "https://www.ukrinform.ua/block-lastnews",
        "https://suspilne.media/news/",
        "https://t.me/ukrpravda_news",
        "https://t.me/suspilnenews",
        # ... другие украинские
    ],
    'european': [
        "https://www.derstandard.at/",
        "https://www.lemonde.fr/",
        "https://www.spiegel.de/international/",
        "https://www.corriere.it/",
        # ... другие европейские
    ],
    'official': [
        "https://t.me/AFUStratCom",
        "https://t.me/GeneralStaffZSU",
        "https://t.me/mvs_ukraine",
        "https://t.me/UA_National_Police",
        # ... официальные каналы
    ]
}

def get_random_web_sources(count: int = 5) -> list:
    import random
    return random.sample(WEB_SOURCES, min(count, len(WEB_SOURCES)))

def get_random_telegram_sources(count: int = 5) -> list:
    import random
    return random.sample(TELEGRAM_SOURCES, min(count, len(TELEGRAM_SOURCES)))

def get_random_sources_mix(web_count: int = 3, telegram_count: int = 2) -> list:
    web = get_random_web_sources(web_count)
    telegram = get_random_telegram_sources(telegram_count)
    
    sources = []
    for link in web:
        sources.append({'link': link, 'type': 'web', 'added_at': '2025-01-01T00:00:00'})
    
    for link in telegram:
        sources.append({'link': link, 'type': 'telegram', 'added_at': '2025-01-01T00:00:00'})
    
    return sources

def get_sources_by_category(category: str, count: int = 5) -> list:
    if category in CATEGORIZED_SOURCES:
        import random
        sources = CATEGORIZED_SOURCES[category]
        return random.sample(sources, min(count, len(sources)))
    return []

__all__ = [
    'WEB_SOURCES',
    'TELEGRAM_SOURCES', 
    'CATEGORIZED_SOURCES',
    'get_random_web_sources',
    'get_random_telegram_sources',
    'get_random_sources_mix',
    'get_sources_by_category'
]