name: CI Pipeline

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build bot image for tests
        run: docker build -t telegram-bot-test --target bot .

      - name: Run tests inside Docker
        run: |
          docker run --rm \
            --network host \
            -e DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db \
            -e REDIS_URL=redis://localhost:6379/0 \
            -e SECRET_KEY=test-secret-key-123 \
            -e DEBUG=False \
            telegram-bot-test \
            python -m pytest /app/tests/ -v --ds=core.settings.testing


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff check
        run: ruff check .

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build bot image
        run: docker build -t telegram-bot --target bot .

      - name: Build admin panel image
        run: docker build -t admin-panel --target admin_panel .
