name: CI Pipeline

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build bot image for tests
        run: docker build -t telegram-bot-test --target bot .

      - name: Run tests inside Docker
        run: |
          docker run --rm \
            -e DATABASE_URL=postgres://postgres:postgres@db:5432/test_db \
            -e REDIS_URL=redis://redis:6379/0 \
            telegram-bot-test \
            python -m pytest /bot/tests -v

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build bot image
        run: docker build -t telegram-bot --target bot .

      - name: Build admin panel image
        run: docker build -t admin-panel --target admin_panel .

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run lint inside Docker
        run: |
          docker build -t telegram-bot-lint --target bot .
          docker run --rm telegram-bot-lint black --check /bot
          docker run --rm telegram-bot-lint isort --check-only /bot
          docker run --rm telegram-bot-lint flake8 /bot
